version: '3.5'

services:

    #Pawns Configuration
    pawns:
        container_name: pawn        
        image: iproyal/pawns-cli:latest
        command: -email=vectorverma890@gmail.com -password=qAWzEqqmDAZ2Mqt -device-name=cli22 -accept-tos
        restart: always
        networks:
            default:
                ipv4_address: 172.106.0.50
    #end of Pawns Configuration

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.106.0.0/16
